import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import { useCallback, useEffect } from "react";
import { useRouter } from "next/router";
import LogoLight from "../assets/logo-light.svg";

const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Todolist</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="bg-veryDarkGrey flex min-h-screen flex-col items-center justify-center">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Main;

const AuthShowcase: React.FC = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();

  const getEnvAndNav = useCallback(async () => {
    if (process.env.NODE_ENV === "development") {
      await router.push("http://localhost:3000/home");
    } else {
      await router.push("https://eylon-kanban.vercel.app/home");
    }
  }, []);

  useEffect(() => {
    if (sessionData) {
      void getEnvAndNav();
    }
  }, [sessionData]);

  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center gap-4 bg-darkPurple">
      <div className="flex h-2/5 w-1/3 flex-col justify-between rounded-xl bg-white px-2 py-10 uppercase shadow-2xl">
        <div className="flex flex-col">
          <div className="mb-10 flex w-full items-center justify-center text-center text-xl font-semibold text-lightPurple lg:text-3xl">
            Coding Assignment by Eylon
          </div>
          <div className="mx-auto font-semibold text-lightPurple">
            A fullstack todolist application
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <button
            className="mx-auto mt-auto w-[80%] rounded-full bg-lightPurple px-10 py-3 text-lg font-semibold uppercase text-white no-underline transition hover:bg-lightPurple/80"
            onClick={() => {
              void signIn("google", {
                callbackUrl: "/home",
              });
            }}
          >
            Login using google
          </button>
          {/* <button
            className="mx-auto mt-auto w-[80%] rounded-full bg-lightPurple px-10 py-3 text-lg font-semibold uppercase text-white no-underline transition hover:bg-lightPurple/80"
            onClick={() => {
              void signIn("discord", {
                callbackUrl: "/home",
              });
            }}
          >
            Login using discord
          </button> */}
        </div>
      </div>
    </div>
  );
};
